UKHomeOffice/pttg-ip-hmrc

src/main/java/uk/gov/digital/ho/pttg/application/SpringConfiguration.java
src/main/java/uk/gov/digital/ho/pttg/application/util/CompositeNameNormalizer.java
src/main/java/uk/gov/digital/ho/pttg/application/util/DiacriticNameNormalizer.java
src/test/java/uk/gov/digital/ho/pttg/application/util/CompositeNameNormalizerTest.java
src/test/java/uk/gov/digital/ho/pttg/application/util/DiacriticNameNormalizerTest.java

This ticket is not complete yet but is being merged in now ahead of live proving.
Still left is:
- What to do about letters that cannot be converted (diacritic overlays and subscript curls).
- Add support for multiple alphabets beyond basic latin.

EE-3856: Added `DiacriticNameNormalizer` to transform to basic latin

---

src/main/java/uk/gov/digital/ho/pttg/application/SpringConfiguration.java
src/main/java/uk/gov/digital/ho/pttg/application/retry/RetryProperties.java
src/main/resources/application.properties
src/test/java/uk/gov/digital/ho/pttg/api/HmrcResourceIntegrationTest.java
src/test/java/uk/gov/digital/ho/pttg/application/SpringConfigurationTest.java

Made it so that the RestTemplate used to communicate with the HMRC API will only use TLSv1.2. 
Because implementing this added another parameter to the SpringConfiguration, pushing it over the static code-check's permitted maximum, I have also refactored this class. There is now a RetryProperties class which wraps the three properties related to HMRC API call retries.
There is no automated test associated with this change because it was not feasible. The code inside the Java/Apache libraries that this code affects is far to complicated to realistically inspect its state through reflection. And developing some sort of mock server that we control the TLS version for in order to test against is a lot of work for a comparatively small gain.

EE-7270 Enforce TLS 1.2 for all HMRC API calls

---

build.gradle
src/test/groovy/acceptance/steps/NameMatchingSteps.groovy
src/test/resources/specs/name-matching/Name_7Strings_HMRC.feature
src/test/resources/specs/name-matching/Name_With_Special_Characters.feature

Updating wiremock version to be able to use newer mock functionalities. Updated mock to match on name/surname initials, in addition to full json object. Added BDD for hyphenated/apostrophe names

EE-8204 Adding BDD for hyphenated and apostrophe names

---

src/main/java/uk/gov/digital/ho/pttg/application/namematching/NameMatchingCandidatesGenerator.java
src/main/java/uk/gov/digital/ho/pttg/application/namematching/NameMatchingCandidatesGeneratorFunctions.java
src/main/java/uk/gov/digital/ho/pttg/application/namematching/PersonName.java
src/test/java/uk/gov/digital/ho/pttg/application/namematching/NameMatchingCandidatesGeneratorFunctionsTest.java
src/test/java/uk/gov/digital/ho/pttg/application/namematching/NameMatchingCandidatesGeneratorTest.java
src/test/java/uk/gov/digital/ho/pttg/application/namematching/PersonNameTest.java
src/test/resources/specs/name-matching/Name_6Strings_HMRC.feature
src/test/resources/specs/name-matching/Name_7Strings_HMRC.feature
src/test/resources/specs/name-matching/Name_Matching_Deduplication.feature
src/test/resources/specs/name-matching/Name_With_Special_Characters.feature

Made it so that we don't send Name Matching requests to HMRC that would be effectively duplicates from their point of view. HMRC only consider the first letter of the first name and the first three significant characters of the surname, so the candidate names for matching attempts are deduplicated accordingly.

Ee 9538 name matching dedupe

---

src/main/java/uk/gov/digital/ho/pttg/application/HmrcHateoasClient.java
src/main/java/uk/gov/digital/ho/pttg/application/namematching/InputNames.java
src/main/java/uk/gov/digital/ho/pttg/application/namematching/NameMatchingCandidatesService.java
src/main/java/uk/gov/digital/ho/pttg/application/namematching/candidates/AliasCombinations.java
src/test/java/uk/gov/digital/ho/pttg/application/HmrcHateoasClientTest.java
src/test/java/uk/gov/digital/ho/pttg/application/namematching/InputNamesTest.java
src/test/java/uk/gov/digital/ho/pttg/application/namematching/NameMatchingCandidatesServiceIT.java
src/test/java/uk/gov/digital/ho/pttg/application/namematching/NameMatchingCandidatesServiceTest.java

Wired the AliasNameCombinations bean into the NameMatchingCandidateService and checked that any aliases in the Individual passed to the HmrcHateoasClient are passed through to the service.
Currently the HmrcService does not pass the HmrcClient any aliases meaning no behaviour has changed yet - that PR will follow this.

EE-9765 Added the AliasNameCombinations  into the NameMatchingCandidateService

---

build.gradle
src/main/java/uk/gov/digital/ho/pttg/application/namematching/candidates/CandidateFunctions.java
src/main/java/uk/gov/digital/ho/pttg/application/namematching/candidates/NamesWithFullStopSpaceCombinations.java
src/main/java/uk/gov/digital/ho/pttg/application/namematching/candidates/NamesWithFullStopSpaceCombinationsFunctions.java
src/test/java/uk/gov/digital/ho/pttg/application/namematching/candidates/CandidateFunctionsTest.java
src/test/java/uk/gov/digital/ho/pttg/application/namematching/candidates/NamesWithFullStopSpaceCombinationsFunctionsContainFullStopSpaceTest.java
src/test/java/uk/gov/digital/ho/pttg/application/namematching/candidates/NamesWithFullStopSpaceCombinationsFunctionsSplitNamesTest.java
src/test/java/uk/gov/digital/ho/pttg/application/namematching/candidates/NamesWithFullStopSpaceCombinationsTest.java

Implemented a new Name Matching Candidates Generator which will take names containing full stop an space and treat them as a single word in name matching (e.g. "St. John").
- I have updated the version of assertJ so that the noneMatch and anyMatch assertions are available
- Also I have fixed a bug in removeNamesIfOverMax method where the first 3 surnames were retained when it should be the last 3. 
-Aliases are not handled by this generator - I will do that in a separate PR

Ee 9349 name with dot space candidate name generator

---

src/main/java/uk/gov/digital/ho/pttg/application/namematching/NameMatchingCandidatesService.java
src/test/java/uk/gov/digital/ho/pttg/application/namematching/NameMatchingCandidatesServiceIT.java
src/test/java/uk/gov/digital/ho/pttg/application/namematching/NameMatchingCandidatesServiceTest.java
src/test/resources/specs/name-matching/Full_stops_in_names.feature

Added the new generator into the Name Matching Candidates Service and removed the WIP tag from related BDD.
I have had to slightly tweak the BDD as the order has changed.

Ee 9349 wire in name with full stop space generator

---

src/main/java/uk/gov/digital/ho/pttg/application/namematching/InputNames.java
src/main/java/uk/gov/digital/ho/pttg/application/namematching/candidates/SpecialCharacters.java
src/main/java/uk/gov/digital/ho/pttg/application/namematching/candidates/SpecialCharactersFunctions.java
src/test/java/uk/gov/digital/ho/pttg/application/namematching/InputNamesTest.java
src/test/java/uk/gov/digital/ho/pttg/application/namematching/candidates/SpecialCharactersFunctionsTest.java

Moved the joinAllAliasSurnames method out of SpecialCharactersFunctions and into InputNames where it is now called allAliasSurnamesAsString.
I have done this because I want to use this method in the FullStopSpace Candidate Generator so it doesn't make sense for this to be owned by SpecialCharacters any more.

EE-9349 Moved the joinAllAliasSurnames method

---

src/main/java/uk/gov/digital/ho/pttg/api/RequestHeaderData.java

Made it so all logs will contain a thread_id entry with the thread number of the current thread.

EE-4133 Added thread_id to all logs

---

src/main/java/uk/gov/digital/ho/pttg/api/HmrcResource.java
src/main/java/uk/gov/digital/ho/pttg/api/RequestHeaderData.java
src/test/java/uk/gov/digital/ho/pttg/api/HmrcResourceDeprecatedGetTest.java
src/test/java/uk/gov/digital/ho/pttg/api/HmrcResourceTest.java
src/test/java/uk/gov/digital/ho/pttg/api/RequestHeaderDataTest.java

This adds milliseconds to the request duration field name and also refactors the request duration calculation moving it to the MDC.

Ee 10256/log fail duration

---

src/main/java/uk/gov/digital/ho/pttg/application/HmrcAccessCodeClient.java
src/test/java/uk/gov/digital/ho/pttg/application/HmrcAccessCodeClientTest.java

Despite changing the URL for the hmrc-access-code service in the helm-chart, I was still getting basic auth errors. And the URL being called seemed to ignore the /hmrcaccesscode bit put in to send the request through the proxy.
The reason was that the line URI.create(baseAccessCodeUrl).resolve(ACCESS_ENDPOINT_PATH) works fine for baseAccessCodeUrl="http://localhost:10080" and ACCESS_ENDPOINT_PATH="/accesscode" resulting in "http://localhost:10080/accesscode"
However, when  baseAccessCodeUrl="http://localhost:10080/hmrcaccesscode" and  ACCESS_ENDPOINT_PATH="/accesscode", the result is still "http://localhost:10080/accesscode"! Must be some funny URI resolution rule!

EE-10292 Fixed resolution of the access-code URI 

---

build.gradle
src/main/java/uk/gov/digital/ho/pttg/application/namematching/candidates/AbbreviatedNamesFunctions.java
src/test/java/uk/gov/digital/ho/pttg/application/namematching/candidates/AbbreviatedNamesFunctionsDoesNotContainAbbreviatedNamesTest.java
src/test/java/uk/gov/digital/ho/pttg/application/namematching/candidates/AbbreviatedNamesFunctionsSplitAroundAbbreviatedNamesTest.java
src/test/java/uk/gov/digital/ho/pttg/application/namematching/candidates/NamesWithAbbreviationSpaceCombinationsAbbreviatedNamesFunctionsTest.java
src/test/java/uk/gov/digital/ho/pttg/application/namematching/candidates/NamesWithAbbreviationSpaceCombinationsAbbreviatedNamesTest.java
src/test/resources/specs/name-matching/Apostrophe_names.feature

This is to make HMRC service supply a name which includes an apostrophe followed by a space as it appears instead of stripping the apostrophe out. Much like it currently does with a full stop and space.
Updated unit tests to reflect the changes after adding another REGEX.

Ee 10741: Handle apostrophe+space like full stop+space in HMRC name matching

---

src/main/java/uk/gov/digital/ho/pttg/application/HmrcClient.java
src/main/java/uk/gov/digital/ho/pttg/application/HmrcClientFunctions.java
src/main/java/uk/gov/digital/ho/pttg/application/HmrcHateoasClient.java
src/main/java/uk/gov/digital/ho/pttg/application/HmrcHateoasClientFunctions.java
src/test/java/uk/gov/digital/ho/pttg/application/HmrcClientFunctionsTest.java
src/test/java/uk/gov/digital/ho/pttg/application/HmrcClientTest.java
src/test/java/uk/gov/digital/ho/pttg/application/HmrcHateoasClientFunctionsTest.java
src/test/java/uk/gov/digital/ho/pttg/application/HmrcHateoasClientTest.java

I've pulled the conversion from LocalDates to tax years (as Strings) out of the the HmrcHateoasClient's buildLinkWithTaxYearRangeQueryParams and moved it into the HmrcClient.
To this end, buildLinkWithTaxYearRangeQueryParams and all the methods that lead up to it from HmrcClient.storeSelfAssessmentResource have been changed to expect tax years as parameters. Also some functions in HmrcHateoasClientFunctions have been moved HmrcClientFunctions. 
I've made this change because I plan to make the calculation of tax years more involved (so that it will not ask for data more than 6 tax years ago). The HmrcClient feels like a more appropriate place to do this work than the HmrcHateoasClient.

Ee 17546 relocate tax year calculation

---

src/main/java/uk/gov/digital/ho/pttg/application/HmrcClientFunctions.java
src/test/java/uk/gov/digital/ho/pttg/application/HmrcClientFunctionsTest.java

Ensure that it will return a correctly formatted tax year when the 2 digit date is less than 10. Not an urgent issue as I don't believe it will affect us until the year 2100. But since I was already working in the area, I though it worth a quick fix.

EE-17546 Fixed the getTaxYear function

---

src/main/java/uk/gov/digital/ho/pttg/application/HmrcClient.java
src/main/java/uk/gov/digital/ho/pttg/application/HmrcClientFunctions.java
src/test/java/uk/gov/digital/ho/pttg/application/HmrcClientFunctionsTest.java
src/test/java/uk/gov/digital/ho/pttg/application/HmrcClientTest.java

Updated the HmrcClient so that it will override the fromTaxYear if it is too far in the past. The number of years that you can go back is a config item. I have intentionally not provided a value for this and set the default to 1000. 
I believe that by setting the maximum allowed range to 1000 years I have not changed the behaviour of this service - I have added tests to confirm this. However it would be prudent to do some regression testing, which I have raised a ticket for (EE-17546).
I will then raise PRs to add the real-life value of 6 years to config (application.properties; eue-api-helm-project; and kube-pttg-ip-hmrc). These will be the "feature" PRs to be tested manually before merging

Ee 17546 Self Assessment rolling window

---

src/main/java/uk/gov/digital/ho/pttg/application/HmrcClient.java
src/main/resources/application.properties
src/test/java/uk/gov/digital/ho/pttg/application/HmrcClientPayeEpochTest.java
src/test/java/uk/gov/digital/ho/pttg/application/HmrcClientTest.java

Added Self Assessment history limit into local config and removed the default so that the value must be set in config.
This ticket should not be merged before EE-17546-sa-rolling-window (https://github.com/UKHomeOffice/pttg-ip-hmrc/pull/187) as it builds on that branch. Diffing against that branch should make reviewing easier also.

Ee 17546 add sa config local

---

src/test/java/uk/gov/digital/ho/pttg/application/HmrcHateoasClientTest.java

Refactored the tests in HmrcHateoasClientTest to use a logCaptor rather than an argThat matcher. This is more readible in my opinion and it is definitely easier to debug. 
I have also made sure that any tests that were not asserting against the value of the log event do so now.
I then identified that the HMRC_NAME_MATCHING_UNSUCCESSFUL log is never verified so I added in this missing test case.
All of this work is to make it easier for me to implement EE-15233. As it is only a unit test refactor, I will merge immediately.

EE 15233 hmrc hateoas client test refactor and improvement

---

src/test/java/bdd/steps/NameMatchingSteps.java

Current Name Matching Metadata BDD is dependent on the order that the logged values are passed to the log.info() method in HmrcHateoasClient. I'm going to be modifying these logs so it will help me if the tests are a little more flexible.
To that end I have changed the BDD steps so that rather than looking at a specific index of the log arguments, they will search through them all for the appropriate one to assert against.
As this is only test refactoring I intend to merge into master immediately.

Ee 15233 flexible name matching bdd

---

src/main/java/uk/gov/digital/ho/pttg/api/HmrcResource.java
src/main/java/uk/gov/digital/ho/pttg/api/RequestHeaderData.java
src/test/java/uk/gov/digital/ho/pttg/api/HmrcResourceContractTest.java
src/test/java/uk/gov/digital/ho/pttg/api/HmrcResourceTest.java
src/test/java/uk/gov/digital/ho/pttg/api/RequestHeaderDataTest.java

Making it so that Nino validation is skipped if the user-id is the one used by the smoke tests.
I intend to merge once approved.

Ee 6825 accept test nino smoke test

---

src/main/java/uk/gov/digital/ho/pttg/api/ComponentTraceHeaderData.java
src/main/java/uk/gov/digital/ho/pttg/audit/AuditClient.java
src/test/java/uk/gov/digital/ho/pttg/api/ComponentTraceHeaderDataTest.java
src/test/java/uk/gov/digital/ho/pttg/api/HmrcResourceIntegrationTest.java
src/test/java/uk/gov/digital/ho/pttg/audit/AuditClientTest.java

When hmrc-service calls audit-service, update the component-trace header with the one in the response from audit-service. I intend to merge to master once approved as nothing observable to IPS should have changed.

Ee 6825 add audit trace

---

src/main/java/uk/gov/digital/ho/pttg/api/ComponentTraceHeaderData.java
src/main/java/uk/gov/digital/ho/pttg/application/HmrcCallWrapper.java
src/test/java/uk/gov/digital/ho/pttg/api/ComponentTraceHeaderDataTest.java
src/test/java/uk/gov/digital/ho/pttg/api/HmrcResourceIntegrationTest.java
src/test/java/uk/gov/digital/ho/pttg/application/HmrcCallWrapperTest.java

Making it so that whenever we call HMRC and get either a successful response or a client error, "HMRC" is added to the x-component-trace header.
The two main methods in HmrcCallWrapper, exchange and followTraverson are virtually identical so I have factored out the exception handling etc. into a new method "handleExceptions" which _wraps_ the actual HMRC call. I'm quite keen on passing a function into another in this manner (looks almost like Python!) but I'm happy to be talked out of it if it's a step to far!
There's a tiny bit of tidying in HmrcCallWrapperTest, just using constants called ANY_X instead of inline values for tests where the values don't matter.
I intend to merge once approved.

Ee 6825 hmrc trace

---

src/main/java/uk/gov/digital/ho/pttg/api/ComponentTraceHeaderData.java
src/main/java/uk/gov/digital/ho/pttg/audit/AuditClient.java
src/test/java/uk/gov/digital/ho/pttg/api/HmrcResourceIntegrationTest.java
src/test/java/uk/gov/digital/ho/pttg/audit/AuditClientTest.java

I missed this out when implementing the x-component-trace headers between components. As this is just a new header being sent between hmrc-service and audit-service I intend to merge once approved unless anybody objects.

EE-6825 Making the hmrc-service send the x-component-trace header to the audit service when it calls it.
